services:
  - type: web
    name: simplydone-app
    env: docker
    plan: free
    healthCheckPath: /api/jobs/health
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: simplydone-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: simplydone-cache
          property: connectionString
      - fromGroup: simplydone-secrets

  - type: redis
    name: simplydone-cache
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0

databases:
  - name: simplydone-db
    databaseName: simplydone_db
    user: simplydone_db_user
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
